INSERT INTO achievements (code, name, description, criteria, points_reward) VALUES
  ('FIRST_REPORT',
   'First Sighting',
   'Report your first waste pin.',
   '{"type":"REPORTS_VERIFIED","threshold":1}'::jsonb,
   10),
  ('FIRST_COLLECTION',
   'Cleanup Rookie',
   'Complete your first verified collection.',
   '{"type":"COLLECTIONS_VERIFIED","threshold":1}'::jsonb,
   25),
  ('TEN_COLLECTIONS',
   'Cleanup Crew',
   'Complete 10 verified collections.',
   '{"type":"COLLECTIONS_VERIFIED","threshold":10}'::jsonb,
   100),
  ('HAZARDOUS_HERO',
   'Hazardous Hero',
   'Verifiably collect a hazardous-category pin.',
   '{"type":"COLLECTIONS_BY_CATEGORY","category":"HAZARDOUS","threshold":1}'::jsonb,
   50);
